/* ==========================================================
   BRAWL ANALYTICS
   REPORT GENERATOR MODULE

   Generates strengths, weaknesses, and summary from score data.
   These are NOT generated by LLM - they're derived from the
   quantitative analysis to ensure consistency with the score.
========================================================== */

/**
 * Generates strengths based on score breakdown and features.
 */
export function generateStrengths(scoreBreakdown, features, score) {
    const strengths = [];
    
    // Originality strengths
    if (features.videoOriginality >= 0.8 && features.ideaOriginality >= 0.8) {
        strengths.push("Completely original content");
    } else if (features.videoOriginality >= 0.6 || features.ideaOriginality >= 0.6) {
        strengths.push("High originality in content or idea");
    }
    
    // Trend strengths
    if (features.trendAlignment >= 0.7 && features.semanticTrendSimilarity >= 0.7) {
        strengths.push("Strong alignment with current trends");
    } else if (features.trendAlignment >= 0.6) {
        strengths.push("Good trend alignment");
    }
    
    // Format strengths
    if (features.historicalPerformance >= 1.2) {
        strengths.push("Format outperforms channel average");
    } else if (features.historicalPerformance >= 0.8) {
        strengths.push("Strong format performance");
    }
    
    if (features.formatStrength >= 0.7) {
        strengths.push("Well-established format for your channel");
    }
    
    // Channel strengths
    if (features.channelConsistency >= 0.7) {
        strengths.push("Consistent channel performance");
    }
    
    // Innovation strengths
    if (features.innovation >= 0.7) {
        strengths.push("Innovative approach");
    }
    
    // Competition strengths
    if (features.competition >= 0.7) {
        strengths.push("Low competition in this topic");
    }
    
    // Historical fit strengths
    if (features.historicalFit >= 0.7) {
        strengths.push("Fits well with your content patterns");
    }
    
    // Ensure at least 2 strengths
    if (strengths.length < 2) {
        if (strengths.length === 0) {
            strengths.push("Content follows established format");
        }
        if (strengths.length === 1) {
            strengths.push("Reasonable potential for engagement");
        }
    }
    
    return strengths.slice(0, 5);
}

/**
 * Generates weaknesses based on score breakdown and features.
 */
export function generateWeaknesses(scoreBreakdown, features, score) {
    const weaknesses = [];
    
    // Originality weaknesses
    if (features.videoOriginality <= 0.3 || features.ideaOriginality <= 0.3) {
        weaknesses.push("Low originality - content may feel reused");
    } else if (features.videoOriginality <= 0.5 || features.ideaOriginality <= 0.5) {
        weaknesses.push("Moderate originality - could be more unique");
    }
    
    // Trend weaknesses
    if (features.trendAlignment <= 0.3) {
        weaknesses.push("Weak trend alignment");
    } else if (features.trendAlignment <= 0.5) {
        weaknesses.push("Limited trend relevance");
    }
    
    // Format weaknesses
    if (features.historicalPerformance <= 0.4) {
        weaknesses.push("Format underperforms historically");
    } else if (features.historicalPerformance <= 0.6) {
        weaknesses.push("Format performance below average");
    }
    
    if (features.formatStrength <= 0.4) {
        weaknesses.push("Format not well-established for your channel");
    }
    
    // Channel weaknesses
    if (features.channelConsistency <= 0.3) {
        weaknesses.push("Inconsistent channel performance");
    }
    
    // Competition weaknesses
    if (features.competition <= 0.3) {
        weaknesses.push("Highly competitive topic");
    } else if (features.competition <= 0.5) {
        weaknesses.push("Moderate competition");
    }
    
    // Format novelty weaknesses
    if (features.formatNovelty >= 0.7) {
        weaknesses.push("New format - uncertain performance");
    }
    
    // Topic freshness weaknesses
    if (features.topicFreshness <= 0.3) {
        weaknesses.push("Topic may feel overused");
    }
    
    // Limit to 3-4 weaknesses
    return weaknesses.slice(0, 4);
}

/**
 * Generates critical issues based on score breakdown and features.
 */
export function generateCriticalIssues(scoreBreakdown, features, score) {
    const criticalIssues = [];
    
    // Critical: Completely copied content
    if (features.videoOriginality <= 0.2 && features.ideaOriginality <= 0.2) {
        criticalIssues.push("Completely copied content - severe originality issue");
    }
    
    // Critical: Terrible format performance
    if (features.historicalPerformance <= 0.2) {
        criticalIssues.push("Format with terrible historical performance");
    }
    
    // Critical: No trend alignment in saturated market
    if (features.trendAlignment <= 0.2 && features.competition <= 0.3) {
        criticalIssues.push("No trend alignment in highly competitive market");
    }
    
    // Critical: Extremely low originality
    if (features.videoOriginality <= 0.1) {
        criticalIssues.push("Extremely low originality - content may be rejected");
    }
    
    // Critical: Very low score
    if (score <= 20) {
        criticalIssues.push("Overall viral potential is critically low");
    }
    
    return criticalIssues;
}

/**
 * Generates summary based on overall score and key factors.
 */
export function generateSummary(score, features, scoreBreakdown) {
    const qualitative = getScoreQualitative(score);
    
    let summary = "";
    
    // Base summary based on score
    if (score >= 85) {
        summary = "This video has excellent viral potential with strong signals across multiple factors.";
    } else if (score >= 70) {
        summary = "This video shows strong viral potential with good alignment with your channel's strengths.";
    } else if (score >= 55) {
        summary = "This video has good potential but could benefit from improvements in key areas.";
    } else if (score >= 40) {
        summary = "This video has moderate potential with some limitations that should be addressed.";
    } else if (score >= 25) {
        summary = "This video shows weak potential due to significant factors limiting performance.";
    } else {
        summary = "This video has very low potential due to critical issues that need to be resolved.";
    }
    
    // Add context based on key factors
    const keyFactors = [];
    
    if (features.historicalPerformance >= 1.2) {
        keyFactors.push("strong format performance");
    } else if (features.historicalPerformance <= 0.4) {
        keyFactors.push("weak format performance");
    }
    
    if (features.trendAlignment >= 0.7) {
        keyFactors.push("excellent trend alignment");
    } else if (features.trendAlignment <= 0.3) {
        keyFactors.push("poor trend alignment");
    }
    
    if (features.videoOriginality >= 0.8 && features.ideaOriginality >= 0.8) {
        keyFactors.push("high originality");
    } else if (features.videoOriginality <= 0.3 || features.ideaOriginality <= 0.3) {
        keyFactors.push("low originality");
    }
    
    if (keyFactors.length > 0) {
        summary += ` Key factors include ${keyFactors.join(", ")}.`;
    }
    
    return summary;
}

/**
 * Gets qualitative score description.
 */
function getScoreQualitative(score) {
    if (score >= 85) return "Excellent";
    if (score >= 70) return "Strong";
    if (score >= 55) return "Good";
    if (score >= 40) return "Moderate";
    if (score >= 25) return "Weak";
    return "Poor";
}

/**
 * Generates action plan suggestions based on analysis.
 */
export function generateActionPlan(features, scoreBreakdown, score) {
    const suggestions = [];
    
    // Originality suggestions
    if (features.videoOriginality <= 0.5) {
        suggestions.push("Increase content originality to differentiate from existing videos");
    }
    
    // Trend suggestions
    if (features.trendAlignment <= 0.5) {
        suggestions.push("Align content more closely with current Brawl Stars trends");
    }
    
    // Format suggestions
    if (features.historicalPerformance <= 0.6) {
        suggestions.push("Consider using a format with better historical performance");
    }
    
    // Competition suggestions
    if (features.competition <= 0.4) {
        suggestions.push("Find a less competitive angle or add unique elements");
    }
    
    // Innovation suggestions
    if (features.innovation <= 0.4) {
        suggestions.push("Add innovative elements to make the content stand out");
    }
    
    // Format novelty suggestions
    if (features.formatNovelty >= 0.7) {
        suggestions.push("Test this new format with a small audience first");
    }
    
    // Ensure at least 3 suggestions
    while (suggestions.length < 3) {
        suggestions.push("Review your best-performing videos for patterns to replicate");
    }
    
    return suggestions.slice(0, 4);
}
